trigger:
- main

resources:
- repo: self

variables:
  subscriptionName: 'MI-NE-Core-Production'
  resourceGroupName: 'MI-NE-corporatewebsite'
  dockerRegistryServiceConnection: '34c2ae91-5d85-4465-b6cc-70e27ce19f44'
  imageRepository: 'corporatewebsite'
  containerRegistry: 'minecontainerregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  containerAppName: 'corporatewebsite'
  containerAppEnvironment: 'caeMINEcorporatewebssite'

  vmImageName: 'ubuntu-latest'

stages:
  - template: templates/build.yaml